# Dataset de entrenamiento — cross-encoder: ampliación del corpus vía Corte Constitucional (embudo aleatorio)

Amplía el corpus de la parte 1 (21 sentencias curadas de redal.org, notebook `ds_parte1_redal.ipynb`)
usando el índice completo de sentencias de la Corte Constitucional (Tutela y Unificación) vía la
API de Datos Abiertos. Aplica un embudo de tres pasos para no gastar tokens de LLM en sentencias
irrelevantes:

1. Índice completo (API pública, sin scraping del buscador JS de la Corte)
2. Prefiltro barato de keywords sobre el texto completo
3. Filtro de pertinencia barato vía LLM (Haiku, solo el inicio del texto)
4. Extracción completa vía LLM (Sonnet, texto completo) solo para lo que pasó los filtros anteriores

Diseñado para correr primero un **piloto chico** (parametrizable, `SAMPLE_SIZE`) y validar que
el pipeline funciona de punta a punta antes de lanzar una muestra grande — la API de Anthropic
tiene cuota limitada. Cada corrida **acumula** sobre la anterior: los resultados (pares y
descartes) se guardan en un único CSV por tipo que se recarga al inicio, y las sentencias que
ya aparecen ahí (aceptadas o descartadas) se excluyen del muestreo — subir `SAMPLE_SIZE` y
volver a correr nunca reprocesa una sentencia ya explorada.

Corre en paralelo a `ds_parte3_research_list.ipynb` (candidatas curadas por research dirigido en
vez de muestreo aleatorio) — ambos comparten la misma blacklist (`dataset_cross_encoder.csv` /
`descartados.csv`, el mismo archivo consolidado que también incluye las sentencias de
`ds_parte1_redal.ipynb`), así que ninguno reprocesa lo que otro ya vio.

**Contenido:**
1. Setup
2. Índice de sentencias (Datos Abiertos)
3. Muestra incremental (excluye sentencias ya procesadas)
4. Descarga y limpieza de texto completo
5. Prefiltro de keywords
6a. Filtro barato de pertinencia (Haiku)
6b. Extracción estructurada completa (Sonnet, solo pertinentes)
7. Construcción de pares (mismo criterio que la parte 1)
8. Loop principal con checkpointing
9. Resultado acumulado

## 1. Setup

In [1]:
# En Colab: descomenta la siguiente línea (o usa `pip install -r requirements.txt` en el venv local)
# !pip install -q beautifulsoup4 requests pandas anthropic python-dotenv

import os
import re
import time
import json

import requests
import pandas as pd
from bs4 import BeautifulSoup
from dotenv import load_dotenv
import anthropic

load_dotenv()  # lee ANTHROPIC_API_KEY del .env en la raíz del repo
client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

HEADERS = {"User-Agent": "Mozilla/5.0"}

# Rutas acumuladas — cada corrida se suma a lo que ya hay, nunca se sobreescribe desde cero.
# dataset_cross_encoder.csv es el archivo consolidado (redal + corte_const + research).
PARES_PATH = "../../data/dataset_cross_encoder.csv"
DESCARTES_PATH = "../../data/descartados.csv"
COLUMNAS_PARES = ["consulta", "articulo", "tipo", "label", "sentencia_origen"]
COLUMNAS_DESCARTES = ["sentencia", "razon"]

def cargar_si_existe(path, columnas):
    if os.path.exists(path):
        return pd.read_csv(path)
    return pd.DataFrame(columns=columnas)

print("Setup listo.")

Setup listo.

## 2. Índice de sentencias (Datos Abiertos)

API pública de Datos Abiertos (Socrata) con el índice completo de sentencias de la Corte
Constitucional — no requiere scraping del buscador JS de la Corte. Se filtra a **T** (Tutela)
y **SU** (Unificación), excluyendo **C** (control de constitucionalidad en abstracto — igual
que en la parte 1, no aportan una consulta de un caso real). El índice completo (`~29.400`
sentencias, `~21.900` T/SU) no trae texto ni tema — solo metadata (número, tipo, fecha,
magistrado) — el texto se descarga aparte en la sección 4.

In [2]:
INDICE_URL = "https://www.datos.gov.co/resource/v2k4-2t8s.json"

# Parametrizable: dejar en None para no filtrar por fecha
FECHA_DESDE = None  # ej. "2000-01-01"
FECHA_HASTA = None  # ej. "2025-12-31"

def construir_where():
    condiciones = ["sentencia_tipo in ('T','SU')"]
    if FECHA_DESDE:
        condiciones.append(f"fecha_sentencia >= '{FECHA_DESDE}'")
    if FECHA_HASTA:
        condiciones.append(f"fecha_sentencia <= '{FECHA_HASTA}'")
    return " AND ".join(condiciones)

def descargar_indice_completo(page_size=5000):
    """Pagina sobre la API de Datos Abiertos hasta traer el índice completo T/SU."""
    filas = []
    offset = 0
    where = construir_where()
    while True:
        params = {"$where": where, "$limit": page_size, "$offset": offset, "$order": ":id"}
        resp = requests.get(INDICE_URL, params=params, headers=HEADERS, timeout=30)
        resp.raise_for_status()
        pagina = resp.json()
        if not pagina:
            break
        filas.extend(pagina)
        offset += page_size
        if len(pagina) < page_size:
            break
    return pd.DataFrame(filas)

df_indice = descargar_indice_completo()
print(f"Sentencias T/SU en el índice: {len(df_indice)}")
df_indice[["sentencia", "sentencia_tipo", "fecha_sentencia"]].head()

Sentencias T/SU en el índice: 21872

  sentencia sentencia_tipo          fecha_sentencia
0  T-012/92              T  1992-02-25T00:00:00.000
1  T-001/92              T  1992-04-03T00:00:00.000
2  T-002/92              T  1992-05-08T00:00:00.000
3  T-003/92              T  1992-05-11T00:00:00.000
4  T-006/92              T  1992-05-12T00:00:00.000

## 3. Muestra incremental (excluye sentencias ya procesadas)

Se cargan los CSV acumulados de corridas anteriores (si existen) y se arma el conjunto de
sentencias ya exploradas — tanto las que terminaron en pares (`sentencia_origen` en
`dataset_cross_encoder.csv`, el archivo consolidado) como las descartadas en cualquier paso del
embudo (`sentencia` en `descartados.csv`). Esa "blacklist" se resta del índice antes de
muestrear, así que subir `SAMPLE_SIZE` y volver a correr esta celda en adelante nunca vuelve a
gastar una llamada a la API en algo ya visto.

`SAMPLE_SIZE` es la cantidad de sentencias **nuevas** a intentar en esta corrida (no el total
acumulado). Se corre primero chico para validar el pipeline de punta a punta (la mayoría del
índice T no es de derecho laboral individual — el rendimiento esperado tras el embudo completo
es bajo en una muestra chica, eso es normal); si corre sin errores y el criterio de pertinencia
se ve razonable, subir a una muestra grande (ej. 500).

In [3]:
SAMPLE_SIZE = 500  # cantidad de sentencias NUEVAS a intentar en esta corrida
RANDOM_STATE = 42  # fija la semilla para que cada corrida sea reproducible

df_pares_acum = cargar_si_existe(PARES_PATH, COLUMNAS_PARES)
df_descartes_acum = cargar_si_existe(DESCARTES_PATH, COLUMNAS_DESCARTES)

ya_procesadas = set(df_pares_acum["sentencia_origen"]) | set(df_descartes_acum["sentencia"])
print(f"Ya procesadas en corridas anteriores: {len(ya_procesadas)}")

df_candidatas = df_indice[~df_indice["sentencia"].isin(ya_procesadas)]
print(f"Candidatas nuevas disponibles: {len(df_candidatas)}")

df_muestra = df_candidatas.sample(n=min(SAMPLE_SIZE, len(df_candidatas)), random_state=RANDOM_STATE).reset_index(drop=True)
print(f"Muestra de esta corrida: {len(df_muestra)} sentencias")
df_muestra["sentencia_tipo"].value_counts()

Ya procesadas en corridas anteriores: 947
Candidatas nuevas disponibles: 20927
Muestra de esta corrida: 500 sentencias

sentencia_tipo
T     488
SU     12
Name: count, dtype: int64

## 4. Descarga y limpieza de texto completo

Patrón de URL de la relatoría de la Corte Constitucional:
`https://www.corteconstitucional.gov.co/relatoria/{año}/{TIPO}{sep}{numero}-{año corto}.htm`.

**Importante, verificado manualmente contra el sitio real:**

- El separador tras el tipo es `-` para `T` y `C` (`T-528-17.htm`) pero **no existe para `SU`**
  (`SU380-21.htm`, no `SU-380-21.htm`) — con guion, la URL resuelve a una página vacía de la
  app Angular del sitio, no a un 404 explícito, así que es un error silencioso si no se
  contempla. Esa página vacía se detecta de forma confiable por la presencia del tag
  `<app-root` en el HTML crudo — **no por tamaño**: se probó primero con un umbral de bytes y
  descartó por error sentencias reales pero cortas (ej. `T-420/99`, 15 KB de contenido legítimo,
  por debajo de un umbral de 20 KB elegido a ojo).
- El HTML declara charset `windows-1252`, no UTF-8 — decodificarlo mal genera acentos
  corruptos.
- El ancla de inicio varía: sentencias de ~1992 dicen *"Sentencia No. T-012/92"* en vez de
  *"Sentencia T-012/92"* — se acepta el `No.` opcional.
- El cierre del fallo **no sigue una fórmula fija**: unas terminan en *"Notifíquese,
  comuníquese, publíquese y cúmplase."*, otras en *"Comuníquese y cúmplase."*, y varias no
  contienen ninguna de esas frases (ej. solo *"LIBRAR la comunicación a que se refiere el
  artículo 36..."* sin mencionar "cúmplase"). Por eso el ancla de cierre es **best-effort**: si
  se encuentra, recorta ruido de aclaraciones de voto/pie de página; si no se encuentra, se
  conserva el texto completo desde el inicio en vez de descartar la sentencia — el truncado a
  `max_chars` en la sección 6 ya acota lo que se le manda al LLM.
- Algunos números de radicado individuales no resuelven (huecos normales en la numeración) —
  se descartan como cualquier otro fallo de descarga real.

In [4]:
def construir_url_relatoria(tipo, sentencia):
    # sentencia viene como "T-528/17" o "SU-380/21" — separa número y año corto
    numero, anio_corto = sentencia.split("-", 1)[1].split("/")
    anio_largo = ("20" if int(anio_corto) <= 50 else "19") + anio_corto
    sep = "" if tipo == "SU" else "-"
    return f"https://www.corteconstitucional.gov.co/relatoria/{anio_largo}/{tipo}{sep}{numero}-{anio_corto}.htm"

RE_INICIO = re.compile(r"Sentencia\s+(?:No\.?\s*)?(?:T|SU|C)\s*-?\s*\d+\s*/\s*\d+", re.IGNORECASE)
RE_FIN = re.compile(r"comuníquese.{0,80}?cúmplase\.?", re.IGNORECASE)

def descargar_texto_sentencia(url):
    """Descarga y limpia el texto de una sentencia. Devuelve None si falla o si
    la página no trae contenido real (shell de la app Angular del sitio)."""
    try:
        resp = requests.get(url, headers=HEADERS, timeout=20)
        resp.raise_for_status()
        if b"<app-root" in resp.content:
            return None  # shell vacío de la SPA del sitio, sin contenido real
        soup = BeautifulSoup(resp.content, "html.parser", from_encoding="windows-1252")
        texto = re.sub(r"\s+", " ", soup.get_text(" ")).strip()

        m_inicio = RE_INICIO.search(texto)
        if not m_inicio:
            return None  # no se encontró el título de la sentencia, contenido sospechoso
        texto = texto[m_inicio.start():]

        m_fin = RE_FIN.search(texto)
        if m_fin:
            texto = texto[:m_fin.end()]  # recorta aclaraciones de voto / pie si se encontró el cierre

        return texto
    except Exception:
        return None

## 5. Prefiltro de keywords

Filtro barato (sin LLM) sobre el texto ya limpio: solo pasan al filtro de pertinencia real las
sentencias que mencionan al menos uno de estos términos de alcance del dominio.

**Lista ampliada tras revisar el alcance real del corpus de la parte 1** (21 sentencias de
redal.org, ya aceptado como válido): la lista original solo cubría contratación/jornada/despido,
pero el corpus real de la parte 1 incluye pagos y descuentos salariales, licencias,
discriminación laboral y debido proceso disciplinario — ninguno de esos términos estaba en la
lista original, así que se habrían perdido casos equivalentes en la parte 2 sin que el LLM
llegara siquiera a evaluarlos.

In [5]:
KEYWORDS_ALCANCE = [
    "estabilidad laboral reforzada", "contrato de trabajo", "despido",
    "terminación del contrato", "jornada laboral", "prestaciones sociales",
    "presunción de relación laboral", "liquidación", "recargo nocturno",
    "recargo dominical", "reintegro laboral",
    # ampliados: cubren temas presentes en el corpus real de la parte 1 que la lista
    # original no capturaba (pagos/descuentos, licencias, discriminación, disciplinario)
    "relación laboral", "contrato realidad", "justa causa", "indemnización",
    "salario", "cesantías", "vacaciones", "ius variandi", "período de prueba",
    "discriminación laboral", "licencia de maternidad", "fuero de maternidad",
    "proceso disciplinario", "descuento salarial", "acoso laboral",
]

def pasa_prefiltro_keywords(texto):
    texto_lower = texto.lower()
    return any(kw in texto_lower for kw in KEYWORDS_ALCANCE)

## 6a. Filtro barato de pertinencia (Claude Haiku)

De las sentencias que pasan el prefiltro de keywords, la gran mayoría termina de todas formas
descartada por no ser pertinente (en la corrida de 200, 114 de 125 — el 91%). Hacer la
extracción completa (Sonnet, texto completo, hasta 1200 tokens de salida) para decidir
pertinencia desperdicia la mayor parte de ese costo en sentencias que se iban a descartar
igual. Este filtro barato usa **Claude Haiku** sobre solo los primeros ~2.500 caracteres (donde
ya suele quedar claro el tema del caso) y responde nada más `pertinente_alcance` + una razón
breve — la extracción completa (sección 6b) corre únicamente para las que pasan aquí.

**Criterio de exclusión** (afinado auditando el dataset acumulado):

1. **Pensión es exclusión incondicional** — jubilación, sustitución pensional o bono
   pensional, `false` sin excepción, sin importar qué tan laboral suene el resto del caso
   (ej. `T-398/15`).
2. **Empleado público vs. trabajador oficial** — Colombia distingue el "empleado público"
   (régimen estatutario/administrativo: docentes oficiales del magisterio, funcionarios de
   carrera) que NO aplica, del "trabajador oficial" (empresas industriales/comerciales del
   Estado, regido por normas tipo CST) que SÍ puede aplicar (ej. `T-008/15`).
3. **Seguridad social en salud (EPS) y trabajadores independientes** — un trámite contra una
   EPS o un reclamo sin relación de empleador no es un litigio laboral (ej. `T-943/07`).
4. **Estudiantes/practicantes en formación** bajo convenio docencia-servicio, sin contrato de
   trabajo (ej. `T-948/08`).

El fragmento que evalúa el gate arranca en `ANTECEDENTES` cuando ese encabezado existe (ahí
están los hechos reales del caso — los primeros ~2.500 caracteres a veces son preámbulo
doctrinal sin el dato clave) y cae de vuelta al inicio del texto si no aparece.

In [6]:
PROMPT_GATE = """Lee este fragmento del inicio de una sentencia de la Corte Constitucional colombiana (puede estar incompleto, es solo el comienzo). Con base en el título/tema del caso, decide si es relevante para un dataset de derecho laboral individual colombiano.

Devuelve SOLO un JSON válido, sin texto adicional ni backticks:
{{"pertinente_alcance": true o false, "razon": "una frase breve"}}

pertinente_alcance=true SOLO si el caso trata sobre una relación laboral INDIVIDUAL regida por el Código Sustantivo del Trabajo (o normas equivalentes para trabajadores oficiales): contratación, jornada, terminación del contrato, salario y pagos (constitutivos o no de salario, descuentos), licencias, vacaciones, cesantías (bajo régimen CST/Ley 50 de 1990), traslados (ius variandi), procedimiento disciplinario del empleador, estabilidad laboral reforzada, discriminación laboral en el empleo.

pertinente_alcance=false SIEMPRE, sin excepción, si:
- El tema central es PENSIÓN o SEGURIDAD SOCIAL en cualquier forma: pensión de vejez, invalidez, sobrevivientes, jubilación, sustitución pensional, bono pensional, régimen de prima media o ahorro individual. Esto aplica sin importar qué tan laboral suene el resto del caso — pensión siempre es false.
- El tema central es seguridad social EN SALUD (EPS): pago de licencias (maternidad, incapacidad) reclamado contra una EPS, cobertura o negación de servicios de salud, afiliación al sistema de salud. Es un trámite de seguridad social en salud, no un litigio laboral entre empleador y trabajador — false aunque mencione licencia de maternidad u otro tema nominalmente laboral.
- El accionante es un TRABAJADOR INDEPENDIENTE (por cuenta propia, sin empleador) — el CST no rige relaciones sin empleador, así que no hay relación laboral individual que evaluar. False.
- El accionante es un ESTUDIANTE o PRACTICANTE en formación (práctica académica, convenio docencia-servicio) sin contrato de trabajo real — no hay relación laboral, aunque el conflicto sea con la institución donde hace la práctica. False.
- El empleador es una entidad estatal Y el vínculo es de "empleado público" bajo régimen estatutario/administrativo (docente oficial del magisterio, funcionario de carrera administrativa, personal nombrado, régimen especial propio como el Fondo de Prestaciones Sociales del Magisterio) — NO CST. Si el fundamento del caso son estatutos especiales (ej. Ley 91 de 1989, Estatuto Docente, Decreto 1042 de 1978, normas de carrera administrativa) en vez de CST/Ley 50 de 1990, es false. Excepción: si el vínculo es de "trabajador oficial" (típico de empresas industriales y comerciales del Estado, regido por normas tipo CST o convención colectiva), sí puede ser pertinente.
- Es derecho colectivo (sindicatos, negociación colectiva, huelga, fuero sindical).
- Es función pública en cualquier otro sentido, o el tema es ajeno al laboral individual.
- Lo laboral aparece solo de forma incidental, sin ser el objeto central de la decisión.

Si el fragmento no deja claro el tema o el tipo de vínculo laboral, responde false.

Fragmento:
{texto}
"""

RE_ANTECEDENTES = re.compile(r"ANTECEDENTES")

def filtro_pertinencia_barato(texto, numero, chars_gate=2500):
    m = RE_ANTECEDENTES.search(texto)
    inicio = m.start() if m else 0
    fragmento = texto[inicio:inicio + chars_gate]
    try:
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=200,
            messages=[{"role": "user", "content": PROMPT_GATE.format(texto=fragmento)}]
        )
        texto_respuesta = next(b.text for b in response.content if b.type == "text")
        raw = texto_respuesta.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        return json.loads(raw)
    except Exception as e:
        print(f"Error en filtro de pertinencia {numero}: {e}")
        return None

## 6b. Extracción estructurada completa (Claude Sonnet, solo pertinentes)

Igual al prompt de extracción de la parte 1 — ya no necesita el campo `pertinente_alcance`
porque eso ya se decidió en la sección 6a; esta celda solo corre para sentencias que ya
pasaron ese filtro.

In [7]:
PROMPT_TEMPLATE = """Lee la siguiente sentencia laboral colombiana. Extrae exactamente esta información y devuelve SOLO un JSON válido, sin texto adicional ni backticks:

{{
  "hechos_resumidos": "los hechos del caso en 2-3 líneas, en lenguaje coloquial, como si un trabajador lo contara (ej. 'me despidieron después de...' o 'trabajé X años y...')",
  "pretension": "qué pedía el demandante, en pocas palabras",
  "articulos_fundamento_directo": ["artículos cuya interpretación/aplicación fue DETERMINANTE para resolver el punto concreto en disputa de este caso. Pregunta guía: si se quitara este artículo, ¿cambiaría el razonamiento de por qué se concedió o negó la pretensión específica? Si sí, va aquí. Formato 'CST Art. X' o 'Ley X de YYYY, Art. Y'"],
  "articulos_marco_general": ["artículos que la sentencia cita pero que son principios generales, reglas de interpretación/remisión, o contexto normativo (ej. favorabilidad, analogía, primacía de la realidad, normas constitucionales genéricas) — NO decidieron el punto específico del caso, cualquier sentencia laboral podría citarlos. Mismo formato."],
  "decision": "concedida" o "negada" o "parcial",
  "elemento_no_acreditado": "si la pretensión fue negada o parcial, qué elemento/requisito no se acreditó según el juez; si fue concedida totalmente, deja este campo vacío"
}}

Sentencia:
{texto}
"""

def extraer_estructura(texto, numero, max_chars=15000):
    texto_truncado = texto[:max_chars]
    try:
        response = client.messages.create(
            model="claude-sonnet-4-5",
            max_tokens=1200,
            messages=[{"role": "user", "content": PROMPT_TEMPLATE.format(texto=texto_truncado)}]
        )
        texto_respuesta = next(b.text for b in response.content if b.type == "text")
        raw = texto_respuesta.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        return json.loads(raw)
    except Exception as e:
        print(f"Error extrayendo {numero}: {e}")
        return None

## 7. Construcción de pares (mismo criterio que la parte 1)

Idéntico a la parte 1: positivo por cada artículo en `articulos_fundamento_directo`, negativo
fácil desde un pool curado de temas laborales distintos, negativo difícil (placeholder) vía
segunda llamada al LLM. Mismo esquema de columnas — ambos CSVs son concatenables sin
transformación adicional.

In [8]:
POOL_NEGATIVOS_FACILES = [
    {"articulo": "CST Art. 236", "tema": "licencia de maternidad"},
    {"articulo": "CST Art. 186", "tema": "vacaciones anuales"},
    {"articulo": "CST Art. 161", "tema": "jornada de trabajo"},
    {"articulo": "Ley 100 de 1993, Art. 13", "tema": "seguridad social"},
]

PROMPT_NEGATIVO_DIFICIL = """Dada esta consulta de un caso laboral colombiano:

{consulta}

Y sabiendo que los artículos correctamente aplicables son: {articulos_correctos}

Dame UN artículo real del derecho laboral colombiano (CST, leyes laborales) que esté relacionado temáticamente con la consulta pero que NO sea el fundamento correcto de la decisión — es decir, un artículo que alguien podría confundir con el correcto pero que no aplica aquí.

Devuelve SOLO un JSON válido, sin texto adicional ni backticks:
{{"articulo_incorrecto": "...", "por_que_se_confunde": "..."}}
"""

def generar_negativo_dificil(consulta, articulos_correctos):
    try:
        response = client.messages.create(
            model="claude-sonnet-4-5",
            max_tokens=300,
            messages=[{"role": "user", "content": PROMPT_NEGATIVO_DIFICIL.format(
                consulta=consulta, articulos_correctos=articulos_correctos)}]
        )
        texto_respuesta = next(b.text for b in response.content if b.type == "text")
        raw = texto_respuesta.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        return json.loads(raw)
    except Exception as e:
        print(f"Error generando negativo difícil: {e}")
        return None

def construir_pares(extraccion, numero):
    consulta = extraccion["hechos_resumidos"]
    articulos_correctos = extraccion.get("articulos_fundamento_directo", [])
    articulos_marco = extraccion.get("articulos_marco_general", [])
    ya_citados = set(articulos_correctos) | set(articulos_marco)

    if not articulos_correctos:
        return None

    pares = [
        {"consulta": consulta, "articulo": art, "tipo": "positivo", "label": 1}
        for art in articulos_correctos
    ]

    candidatos_faciles = [n for n in POOL_NEGATIVOS_FACILES if n["articulo"] not in ya_citados]
    if candidatos_faciles:
        pares.append({
            "consulta": consulta,
            "articulo": candidatos_faciles[0]["articulo"],
            "tipo": "negativo_facil",
            "label": 0,
        })

    negativo_dificil = generar_negativo_dificil(consulta, articulos_correctos)
    if negativo_dificil:
        pares.append({
            "consulta": consulta,
            "articulo": negativo_dificil["articulo_incorrecto"],
            "tipo": "negativo_dificil_placeholder",
            "label": 0,
        })

    df = pd.DataFrame(pares)
    df["sentencia_origen"] = numero
    return df

## 8. Loop principal con checkpointing

Recorre la muestra, aplicando el embudo completo por sentencia con manejo de errores
individual (una sentencia que falla no tumba el loop). Guarda checkpoint del CSV de pares y
del log de descartes cada `CHECKPOINT_EVERY` sentencias procesadas, para no perder todo si se
cae la conexión a mitad de una corrida larga — cada checkpoint escribe lo acumulado de
corridas anteriores **más** lo nuevo de esta corrida, nunca solo esta corrida. Pausa entre
requests HTTP y entre llamadas a la API de Anthropic para no golpear ninguno de los dos
servicios en paralelo sin pausas.

In [9]:
CHECKPOINT_EVERY = 10

nuevos_pares = []  # lista de DataFrames, uno por sentencia aceptada en ESTA corrida
nuevos_descartes = []  # {"sentencia": ..., "razon": ...}, de ESTA corrida

def guardar_checkpoint():
    partes = [df_pares_acum] + nuevos_pares
    pd.concat(partes, ignore_index=True).to_csv(PARES_PATH, index=False)
    pd.concat([df_descartes_acum, pd.DataFrame(nuevos_descartes, columns=COLUMNAS_DESCARTES)],
              ignore_index=True).to_csv(DESCARTES_PATH, index=False)

for i, row in df_muestra.iterrows():
    numero = row["sentencia"]
    tipo = row["sentencia_tipo"]
    print(f"[{i+1}/{len(df_muestra)}] Procesando {numero}...")

    try:
        url = construir_url_relatoria(tipo, numero)
        texto = descargar_texto_sentencia(url)
        time.sleep(0.5)

        if texto is None:
            nuevos_descartes.append({"sentencia": numero, "razon": "sin_texto_o_url_no_resuelve"})
            continue

        if not pasa_prefiltro_keywords(texto):
            nuevos_descartes.append({"sentencia": numero, "razon": "no_pasa_prefiltro_keywords"})
            continue

        gate = filtro_pertinencia_barato(texto, numero)
        time.sleep(0.5)

        if gate is None:
            nuevos_descartes.append({"sentencia": numero, "razon": "error_filtro_pertinencia"})
            continue

        if not gate.get("pertinente_alcance"):
            nuevos_descartes.append({
                "sentencia": numero,
                "razon": f"llm_no_pertinente: {gate.get('razon', '')}",
            })
            continue

        extraccion = extraer_estructura(texto, numero)
        time.sleep(1)

        if extraccion is None:
            nuevos_descartes.append({"sentencia": numero, "razon": "error_extraccion_llm"})
            continue

        df_par = construir_pares(extraccion, numero)
        time.sleep(1)

        if df_par is not None:
            nuevos_pares.append(df_par)
        else:
            nuevos_descartes.append({"sentencia": numero, "razon": "sin_articulos_fundamento_directo"})

    except Exception as e:
        nuevos_descartes.append({"sentencia": numero, "razon": f"error_inesperado: {e}"})

    if (i + 1) % CHECKPOINT_EVERY == 0:
        guardar_checkpoint()
        print(f"  checkpoint guardado ({i+1}/{len(df_muestra)})")

guardar_checkpoint()
print(f"\nProcesamiento completo. Pares generados de {len(nuevos_pares)} sentencias pertinentes nuevas.")
print(f"Descartadas en esta corrida: {len(nuevos_descartes)} de {len(df_muestra)}")

[1/500] Procesando T-354/24...

[2/500] Procesando T-889A/06...

[3/500] Procesando T-320/07...

[4/500] Procesando T-1132/00...

[5/500] Procesando T-195/23...

[6/500] Procesando T-091/19...

[7/500] Procesando SU-509/01...

[8/500] Procesando T-011/11...

[9/500] Procesando T-482/23...

[10/500] Procesando T-102/01...

[11/500] Procesando T-129/07...

[12/500] Procesando T-276/12...

[13/500] Procesando T-223/04...

[14/500] Procesando T-1138/08...

[15/500] Procesando T-372/00...

[16/500] Procesando T-016/02...

[17/500] Procesando T-315/18...

[18/500] Procesando T-408/07...

[19/500] Procesando T-320/14...

[20/500] Procesando T-330/98...

[21/500] Procesando T-727/08...

[22/500] Procesando T-799/13...

[23/500] Procesando T-315/06...

[24/500] Procesando T-288/96...

[25/500] Procesando T-347/08...

[26/500] Procesando T-297/94...

[27/500] Procesando T-634/08...

[28/500] Procesando T-709/11...

[29/500] Procesando T-779/98...

[30/500] Procesando SU-501/15...

[31/500] Procesando T-1679/00...

[32/500] Procesando T-1629/00...

[33/500] Procesando T-1209/05...

[34/500] Procesando T-631/00...

[35/500] Procesando T-730/04...

[36/500] Procesando T-633/01...

[37/500] Procesando T-242/98...

[38/500] Procesando T-146A/03...

[39/500] Procesando T-022/19...

[40/500] Procesando T-090/06...

[41/500] Procesando T-340/20...

[42/500] Procesando T-681/99...

[43/500] Procesando T-616/05...

[44/500] Procesando T-1280/05...

[45/500] Procesando T-1200/04...

[46/500] Procesando T-483/16...

[47/500] Procesando T-003/95...

[48/500] Procesando T-960/01...

[49/500] Procesando T-1104/02...

[50/500] Procesando T-439/25...

[51/500] Procesando T-199/14...

[52/500] Procesando T-012/03...

[53/500] Procesando T-340/05...

[54/500] Procesando T-001/07...

[55/500] Procesando T-519/11...

[56/500] Procesando T-340/12...

[57/500] Procesando T-1045/10...

[58/500] Procesando SU-488/20...

[59/500] Procesando T-1157/04...

[60/500] Procesando T-455/98...

[61/500] Procesando T-604/14...

[62/500] Procesando T-849/09...

[63/500] Procesando T-705/96...

[64/500] Procesando T-489/99...

[65/500] Procesando T-158/12...

[66/500] Procesando T-546/08...

[67/500] Procesando T-1588/00...

[68/500] Procesando T-451/23...

[69/500] Procesando T-1122/00...

[70/500] Procesando T-834/04...

[71/500] Procesando T-588/11...

[72/500] Procesando T-885/12...

[73/500] Procesando T-003/03...

[74/500] Procesando T-746/04...

[75/500] Procesando T-422/96...

[76/500] Procesando T-145/96...

[77/500] Procesando T-064/11...

[78/500] Procesando T-424/10...

[79/500] Procesando T-891/00...

[80/500] Procesando T-016/23...

[81/500] Procesando T-214/20...

[82/500] Procesando T-646/15...

[83/500] Procesando T-681/08...

[84/500] Procesando T-481/00...

[85/500] Procesando T-191/11...

[86/500] Procesando T-726/11...

[87/500] Procesando T-087/14...

[88/500] Procesando T-014/94...

[89/500] Procesando T-539/92...

[90/500] Procesando SU-242/15...

[91/500] Procesando T-269/10...

[92/500] Procesando T-778/12...

[93/500] Procesando T-614/06...

[94/500] Procesando T-530/09...

[95/500] Procesando T-955/03...

[96/500] Procesando T-836/11...

[97/500] Procesando T-800/11...

[98/500] Procesando T-760/12...

[99/500] Procesando T-564/13...

[100/500] Procesando T-962/02...

[101/500] Procesando T-1013/99...

[102/500] Procesando T-348/96...

[103/500] Procesando T-796/98...

[104/500] Procesando T-893/14...

[105/500] Procesando T-184/12...

[106/500] Procesando T-857/99...

[107/500] Procesando T-143/13...

[108/500] Procesando T-918/03...

[109/500] Procesando T-364/24...

[110/500] Procesando T-615/07...

[111/500] Procesando T-240/16...

[112/500] Procesando T-089/12...

[113/500] Procesando T-116/11...

[114/500] Procesando T-047/11...

[115/500] Procesando T-185/16...

[116/500] Procesando T-045/15...

[117/500] Procesando T-816/08...

[118/500] Procesando T-482/93...

[119/500] Procesando T-259/03...

[120/500] Procesando T-718/10...

[121/500] Procesando T-355/05...

[122/500] Procesando T-040/12...

[123/500] Procesando T-542/15...

[124/500] Procesando T-1002/01...

[125/500] Procesando T-181/24...

[126/500] Procesando T-062/11...

[127/500] Procesando T-485/94...

[128/500] Procesando T-966/11...

[129/500] Procesando T-109/99...

[130/500] Procesando T-974/14...

[131/500] Procesando T-295/24...

[132/500] Procesando T-407/01...

[133/500] Procesando T-647/14...

[134/500] Procesando T-822/08...

[135/500] Procesando T-694/12...

[136/500] Procesando T-500/16...

[137/500] Procesando T-509/19...

[138/500] Procesando SU-074/22...

[139/500] Procesando SU-087/99...

[140/500] Procesando T-208/15...

[141/500] Procesando T-192/08...

[142/500] Procesando T-407/99...

[143/500] Procesando T-041/05...

[144/500] Procesando T-260/98...

[145/500] Procesando T-1062/12...

[146/500] Procesando T-172/24...

[147/500] Procesando T-994/10...

[148/500] Procesando T-406/17...

[149/500] Procesando T-1567/00...

[150/500] Procesando T-435/97...

[151/500] Procesando T-344/14...

[152/500] Procesando T-024/16...

[153/500] Procesando T-817/09...

[154/500] Procesando T-164/05...

[155/500] Procesando T-040/98...

[156/500] Procesando T-209/95...

[157/500] Procesando T-409/00...

[158/500] Procesando T-980/99...

[159/500] Procesando T-1307/05...

[160/500] Procesando T-323/98...

[161/500] Procesando T-933/99...

[162/500] Procesando T-852/06...

[163/500] Procesando T-545/03...

[164/500] Procesando T-932/13...

[165/500] Procesando T-762/00...

[166/500] Procesando T-121/02...

[167/500] Procesando T-1694/00...

[168/500] Procesando T-355/93...

[169/500] Procesando T-237/11...

[170/500] Procesando T-389/10...

[171/500] Procesando T-522/12...

[172/500] Procesando T-1064/04...

[173/500] Procesando T-667/17...

[174/500] Procesando T-198/14...

[175/500] Procesando T-089/08...

[176/500] Procesando T-360/00...

[177/500] Procesando T-381/12...

[178/500] Procesando T-497/06...

[179/500] Procesando T-217/18...

[180/500] Procesando T-077/01...

[181/500] Procesando T-362/05...

[182/500] Procesando T-853/99...

[183/500] Procesando T-383/93...

[184/500] Procesando T-860/13...

[185/500] Procesando T-567/05...

[186/500] Procesando T-313/11...

[187/500] Procesando T-764/03...

[188/500] Procesando T-521/00...

[189/500] Procesando T-001/26...

[190/500] Procesando T-972/06...

[191/500] Procesando T-006/04...

[192/500] Procesando T-1231/01...

[193/500] Procesando T-416/05...

[194/500] Procesando T-691/09...

[195/500] Procesando T-137/09...

[196/500] Procesando T-371/23...

[197/500] Procesando T-167/04...

[198/500] Procesando T-178/04...

[199/500] Procesando T-1204/01...

[200/500] Procesando SU-240/15...

[201/500] Procesando T-560/15...

[202/500] Procesando T-920/06...

[203/500] Procesando T-319/11...

[204/500] Procesando T-348/15...

[205/500] Procesando T-080/00...

[206/500] Procesando T-149/12...

[207/500] Procesando T-553/23...

[208/500] Procesando T-720/09...

[209/500] Procesando T-703/16...

[210/500] Procesando T-825/05...

[211/500] Procesando T-413/94...

[212/500] Procesando T-809/03...

[213/500] Procesando T-640/08...

[214/500] Procesando SU-355/22...

[215/500] Procesando T-421/25...

[216/500] Procesando T-131A/96...

[217/500] Procesando T-281/11...

[218/500] Procesando T-557/03...

[219/500] Procesando T-448/09...

[220/500] Procesando T-401/22...

[221/500] Procesando T-047/13...

[222/500] Procesando T-021/99...

[223/500] Procesando T-471/10...

[224/500] Procesando T-711/11...

[225/500] Procesando T-651/08...

[226/500] Procesando T-656/00...

[227/500] Procesando T-135/11...

[228/500] Procesando T-342/20...

[229/500] Procesando T-501/09...

[230/500] Procesando T-567/06...

[231/500] Procesando T-189/18...

[232/500] Procesando T-035/00...

[233/500] Procesando T-523/99...

[234/500] Procesando T-664/08...

[235/500] Procesando T-145/99...

[236/500] Procesando T-517/06...

[237/500] Procesando T-566/13...

[238/500] Procesando T-992/05...

[239/500] Procesando T-419/10...

[240/500] Procesando T-288/11...

[241/500] Procesando T-719/03...

[242/500] Procesando T-305/24...

[243/500] Procesando T-625/16...

[244/500] Procesando T-489/08...

[245/500] Procesando T-367/17...

[246/500] Procesando T-405/17...

[247/500] Procesando T-022/18...

[248/500] Procesando T-825/10...

[249/500] Procesando T-663/05...

[250/500] Procesando T-423/13...

[251/500] Procesando T-161A/19...

[252/500] Procesando T-624/97...

[253/500] Procesando T-1075/00...

[254/500] Procesando T-482/04...

[255/500] Procesando T-703/04...

[256/500] Procesando T-488/06...

[257/500] Procesando T-627/99...

[258/500] Procesando T-170/09...

[259/500] Procesando T-433/11...

[260/500] Procesando T-1387/00...

[261/500] Procesando T-862/02...

[262/500] Procesando T-1011/99...

[263/500] Procesando T-384/11...

[264/500] Procesando T-527/20...

[265/500] Procesando T-075/19...

[266/500] Procesando T-080/95...

[267/500] Procesando T-681/07...

[268/500] Procesando T-203/14...

[269/500] Procesando T-260/13...

[270/500] Procesando T-028/05...

[271/500] Procesando T-385/23...

[272/500] Procesando T-215/03...

[273/500] Procesando T-1097/08...

[274/500] Procesando T-615/16...

[275/500] Procesando T-971/05...

[276/500] Procesando T-601/13...

[277/500] Procesando T-401/25...

[278/500] Procesando T-235/15...

[279/500] Procesando T-737/04...

[280/500] Procesando T-201/17...

[281/500] Procesando T-871/06...

[282/500] Procesando T-452/15...

[283/500] Procesando SU-1554/00...

[284/500] Procesando T-790/13...

[285/500] Procesando T-491/18...

[286/500] Procesando T-864/05...

[287/500] Procesando T-114/22...

[288/500] Procesando T-681/15...

[289/500] Procesando T-697/17...

[290/500] Procesando T-112/04...

[291/500] Procesando T-954/14...

[292/500] Procesando T-640/14...

[293/500] Procesando T-890/09...

[294/500] Procesando T-195/04...

[295/500] Procesando T-603/99...

[296/500] Procesando T-364/02...

[297/500] Procesando T-770/05...

[298/500] Procesando T-434/93...

[299/500] Procesando T-161/23...

[300/500] Procesando T-494/13...

[301/500] Procesando T-437/99...

[302/500] Procesando T-270/08...

[303/500] Procesando T-905/02...

[304/500] Procesando T-797/01...

[305/500] Procesando T-427/04...

[306/500] Procesando T-295/15...

[307/500] Procesando T-728/06...

[308/500] Procesando T-1480/00...

[309/500] Procesando T-1327/01...

[310/500] Procesando T-220/00...

[311/500] Procesando T-400/19...

[312/500] Procesando T-065/18...

[313/500] Procesando T-441/14...

[314/500] Procesando SU-420/19...

[315/500] Procesando T-433/06...

[316/500] Procesando T-328/08...

[317/500] Procesando T-548/07...

[318/500] Procesando T-042/10...

[319/500] Procesando T-1010/10...

[320/500] Procesando T-926/12...

[321/500] Procesando T-343/10...

[322/500] Procesando T-369/15...

[323/500] Procesando T-656/11...

[324/500] Procesando T-956/13...

[325/500] Procesando T-471/05...

[326/500] Procesando T-779/08...

[327/500] Procesando T-707/99...

[328/500] Procesando T-539/07...

[329/500] Procesando T-118A/13...

[330/500] Procesando T-767/02...

[331/500] Procesando T-433/92...

[332/500] Procesando T-348/08...

[333/500] Procesando T-636/13...

[334/500] Procesando T-1075/01...

[335/500] Procesando SU-071/22...

[336/500] Procesando T-937/00...

[337/500] Procesando T-524/15...

[338/500] Procesando T-060/20...

[339/500] Procesando T-265/99...

[340/500] Procesando T-535/99...

[341/500] Procesando T-157/94...

[342/500] Procesando T-236/21...

[343/500] Procesando T-1160/01...

[344/500] Procesando T-437/96...

[345/500] Procesando T-164/03...

[346/500] Procesando T-974/04...

[347/500] Procesando T-689/12...

[348/500] Procesando T-576/14...

[349/500] Procesando T-471/93...

[350/500] Procesando T-613/14...

[351/500] Procesando T-133/04...

[352/500] Procesando T-368/15...

[353/500] Procesando T-1306/01...

[354/500] Procesando T-001/16...

[355/500] Procesando T-555/09...

[356/500] Procesando T-465/23...

[357/500] Procesando T-1196/03...

[358/500] Procesando T-765/04...

[359/500] Procesando T-461/12...

[360/500] Procesando T-319/04...

[361/500] Procesando T-170/00...

[362/500] Procesando T-731/98...

[363/500] Procesando T-648/14...

[364/500] Procesando T-431/12...

[365/500] Procesando T-312/24...

[366/500] Procesando T-230/17...

[367/500] Procesando T-465A/96...

[368/500] Procesando T-662/01...

[369/500] Procesando T-1293/00...

[370/500] Procesando T-418/06...

[371/500] Procesando T-946/14...

[372/500] Procesando T-775/07...

[373/500] Procesando T-760A/00...

[374/500] Procesando T-541/01...

[375/500] Procesando T-424/24...

[376/500] Procesando T-1025/06...

[377/500] Procesando T-065/10...

[378/500] Procesando T-298/03...

[379/500] Procesando T-354/99...

[380/500] Procesando T-680/13...

[381/500] Procesando T-1583/00...

[382/500] Procesando T-847/09...

[383/500] Procesando T-743/07...

[384/500] Procesando T-246/16...

[385/500] Procesando T-717/05...

[386/500] Procesando T-149/23...

[387/500] Procesando T-083/97...

[388/500] Procesando T-965/09...

[389/500] Procesando SU-298/15...

[390/500] Procesando T-763/03...

[391/500] Procesando T-699/11...

[392/500] Procesando T-796/03...

[393/500] Procesando T-359/05...

[394/500] Procesando T-221/08...

[395/500] Procesando T-045/95...

[396/500] Procesando T-267/99...

[397/500] Procesando T-738/99...

[398/500] Procesando T-941/06...

[399/500] Procesando T-068/12...

[400/500] Procesando T-196/05...

[401/500] Procesando T-126/97...

[402/500] Procesando T-105/02...

[403/500] Procesando T-191/15...

[404/500] Procesando T-184/24...

[405/500] Procesando T-638/11...

[406/500] Procesando T-561/09...

[407/500] Procesando T-562/17...

[408/500] Procesando T-689/06...

[409/500] Procesando T-013/12...

[410/500] Procesando T-268/04...

[411/500] Procesando T-320/18...

[412/500] Procesando T-1019/04...

[413/500] Procesando T-632/05...

[414/500] Procesando T-620/95...

[415/500] Procesando T-441/07...

[416/500] Procesando T-676/11...

[417/500] Procesando T-182/96...

[418/500] Procesando T-097/23...

[419/500] Procesando T-1161/08...

[420/500] Procesando T-300/93...

[421/500] Procesando T-711/16...

[422/500] Procesando T-370/22...

[423/500] Procesando T-281/20...

[424/500] Procesando T-542/13...

[425/500] Procesando T-698/16...

[426/500] Procesando T-030/98...

[427/500] Procesando T-304/93...

[428/500] Procesando T-116/25...

[429/500] Procesando T-548/09...

[430/500] Procesando T-334/09...

[431/500] Procesando T-339/09...

[432/500] Procesando T-935/14...

[433/500] Procesando T-586A/11...

[434/500] Procesando T-1153/00...

[435/500] Procesando T-514/17...

[436/500] Procesando T-460/00...

[437/500] Procesando T-525/10...

[438/500] Procesando T-079/02...

[439/500] Procesando T-237/07...

[440/500] Procesando T-1131/01...

[441/500] Procesando T-391/11...

[442/500] Procesando T-188/11...

[443/500] Procesando T-1095/07...

[444/500] Procesando T-439/20...

[445/500] Procesando T-380/05...

[446/500] Procesando T-1028/01...

[447/500] Procesando T-843/06...

[448/500] Procesando T-1282/00...

[449/500] Procesando T-352/94...

[450/500] Procesando T-836/14...

[451/500] Procesando T-447/20...

[452/500] Procesando T-004/00...

[453/500] Procesando T-022/25...

[454/500] Procesando T-807/04...

[455/500] Procesando T-270/95...

[456/500] Procesando T-285/21...

[457/500] Procesando T-074/18...

[458/500] Procesando T-906/04...

[459/500] Procesando T-1135/01...

[460/500] Procesando T-661/14...

[461/500] Procesando T-846/08...

[462/500] Procesando T-422/99...

[463/500] Procesando T-345/10...

[464/500] Procesando T-901/01...

[465/500] Procesando T-842A/13...

[466/500] Procesando T-347/24...

[467/500] Procesando T-025/02...

[468/500] Procesando T-925/10...

[469/500] Procesando T-585/19...

[470/500] Procesando T-400/96...

[471/500] Procesando T-203/13...

[472/500] Procesando T-956/03...

[473/500] Procesando T-633/06...

[474/500] Procesando T-888/99...

[475/500] Procesando T-284/95...

[476/500] Procesando T-789/14...

[477/500] Procesando T-647/15...

[478/500] Procesando T-503/97...

[479/500] Procesando T-045/16...

[480/500] Procesando T-410/11...

  checkpoint guardado (480/500)
[481/500] Procesando T-366/21...

[482/500] Procesando T-1245/00...

[483/500] Procesando T-096/06...

[484/500] Procesando T-230/24...

[485/500] Procesando T-587/13...

[486/500] Procesando T-001/15...

[487/500] Procesando T-332/16...

[488/500] Procesando T-381/22...

[489/500] Procesando T-038/22...

[490/500] Procesando T-606/16...

[491/500] Procesando T-909/01...

[492/500] Procesando T-486/06...

[493/500] Procesando T-007/04...

[494/500] Procesando T-955/12...

[495/500] Procesando T-800/14...

[496/500] Procesando T-214/09...

[497/500] Procesando T-139/94...

[498/500] Procesando T-468/99...

[499/500] Procesando T-027/06...

[500/500] Procesando T-212/21...

Procesamiento completo. Pares generados de 19 sentencias pertinentes nuevas.
Descartadas en esta corrida: 481 de 500

## 9. Resultado acumulado

In [10]:
df_dataset_parte2 = pd.concat([df_pares_acum] + nuevos_pares, ignore_index=True) if nuevos_pares else df_pares_acum
df_descartes_total = pd.concat([df_descartes_acum, pd.DataFrame(nuevos_descartes, columns=COLUMNAS_DESCARTES)], ignore_index=True)

print(f"--- Esta corrida ({len(df_muestra)} sentencias nuevas intentadas) ---")
print(f"Pares nuevos: {sum(len(df) for df in nuevos_pares)} de {len(nuevos_pares)} sentencias pertinentes")

print(f"\n--- Acumulado total ---")
print(f"Total de pares: {len(df_dataset_parte2)}")
if not df_dataset_parte2.empty:
    print(f"Sentencias representadas: {df_dataset_parte2['sentencia_origen'].nunique()}")
    print(df_dataset_parte2["tipo"].value_counts())

print("\nRazones de descarte (acumulado):")
if not df_descartes_total.empty:
    print(df_descartes_total["razon"].apply(lambda r: r.split(":")[0]).value_counts())

print(f"\nGuardado en {PARES_PATH}")
print(f"Log de descartes en {DESCARTES_PATH}")
df_dataset_parte2.head()

--- Esta corrida (500 sentencias nuevas intentadas) ---
Pares nuevos: 69 de 19 sentencias pertinentes

--- Acumulado total ---
Total de pares: 498
Sentencias representadas: 125
tipo
positivo                        248
negativo_facil                  125
negativo_dificil_placeholder    125
Name: count, dtype: int64

Razones de descarte (acumulado):
razon
llm_no_pertinente                   772
no_pasa_prefiltro_keywords          453
sin_articulos_fundamento_directo     49
sin_texto_o_url_no_resuelve          45
revision_manual                       5
Name: count, dtype: int64

Guardado en ../../data/dataset_cross_encoder.csv
Log de descartes en ../../data/descartados.csv

,consulta,articulo,tipo,label,sentencia_origen
0,Trabajé como operador de bus articulado desde ...,CST Art. 127,positivo,1,SL-3630/22
1,Trabajé como operador de bus articulado desde ...,CST Art. 128,positivo,1,SL-3630/22
2,Trabajé como operador de bus articulado desde ...,CST Art. 236,negativo_facil,0,SL-3630/22
3,Trabajé como operador de bus articulado desde ...,CST Art. 130,negativo_dificil_placeholder,0,SL-3630/22
4,Trabajé para el ISS desde septiembre de 2000 h...,"Decreto 2127 de 1945, Art. 20",positivo,1,SL-2858/22